apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  ports:
  - port: 9200
    name: elk-e
  - port: 5000
    name: elk-l
  - port: 5601
    name: elk-k
  selector:
    app: elk
  #clusterIP: None
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ci-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: elk
spec:
  selector:
    matchLabels:
      app: elk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
      - image: avasseur/elasticsearch:latest
        name: elk
        ports:
        - containerPort: 9200
          name: elk-e
        - containerPort: 5000
          name: elk-l
        - containerPort: 5601
          name: elk-k
        volumeMounts:
        - name: elk-persistent-storage
          mountPath: /var/lib/elasticsearch
      volumes:
      - name: elk-persistent-storage
        persistentVolumeClaim:
          claimName: elk-pv-claim
